#!/bin/bash
set -euo pipefail

scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${scriptDir}/../lib/common.sh"
repoRoot="$(ryanjson_repo_root_from_source "${BASH_SOURCE[0]}" 2)"
listFile="${repoRoot}/test/unityTest/runner/test_list.inc"
caseRoot="${repoRoot}/test/unityTest/cases"

if [[ ! -d "${caseRoot}" ]]; then
	echo "[error] unity cases directory not found: ${caseRoot}" >&2
	exit 1
fi

mapfile -t implLines < <(rg -n --pcre2 "void[[:space:]]+(test[A-Za-z0-9_]+Runner)[[:space:]]*\\(" "${caseRoot}")

if [[ ${#implLines[@]} -eq 0 ]]; then
	echo "[error] no runner implementations found under ${caseRoot}" >&2
	exit 1
fi

declare -A seen=()
declare -a implemented=()
mapfile -t implSorted < <(
	printf '%s\n' "${implLines[@]}" | awk -F: '
	{
		file = $1;
		line = $2;
		if (match($0, /void[[:space:]]+(test[A-Za-z0-9_]+Runner)[[:space:]]*\(/, m)) {
			print file "\t" line "\t" m[1];
		}
	}
	' | sort -t $'\t' -k1,1 -k2,2n
)
for line in "${implSorted[@]}"; do
	name="$(echo "${line}" | cut -f3)"
	if [[ -n "${name}" && -z "${seen[${name}]+x}" ]]; then
		implemented+=("${name}")
		seen["${name}"]=1
	fi
done

tmpFile="$(mktemp)"
{
	echo "// Auto-generated by scripts/ci/checkUnityRunnerList.sh. Do not edit by hand."
	for name in "${implemented[@]}"; do
		if [[ "${name}" == "testRfc8259Runner" ]]; then
			echo "#if !defined(RyanJsonTestPlatformQemu)"
			echo "UNITY_TEST_LIST_ENTRY(${name})"
			echo "#endif"
		else
			echo "UNITY_TEST_LIST_ENTRY(${name})"
		fi
	done
} > "${tmpFile}"

if [[ ! -f "${listFile}" ]] || ! cmp -s "${tmpFile}" "${listFile}"; then
	mv "${tmpFile}" "${listFile}"
	echo "[update] unity runner list regenerated: ${listFile}"
else
	rm -f "${tmpFile}"
	echo "[ok] unity runner list already up to date"
fi
