// Auto-generated by scripts/tools/gen_rfc8259_embedded.py. Do not edit by hand.
#include "rfc8259Embedded.h"

static const unsigned char rfc8259Embedded000iNumberDoubleHugeNegExpJson[] =
    "[123.456e-789]"
;

static const unsigned char rfc8259Embedded001iNumberHugeExpJson[] =
    "[0.4e0066999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999"
    "9999999999969999999006]"
;

static const unsigned char rfc8259Embedded002iNumberNegIntHugeExpJson[] =
    "[-1e+9999]"
;

static const unsigned char rfc8259Embedded003iNumberPosDoubleHugeExpJson[] =
    "[1.5e+9999]"
;

static const unsigned char rfc8259Embedded004iNumberRealNegOverflowJson[] =
    "[-123123e100000]"
;

static const unsigned char rfc8259Embedded005iNumberRealPosOverflowJson[] =
    "[123123e100000]"
;

static const unsigned char rfc8259Embedded006iNumberRealUnderflowJson[] =
    "[123e-10000000]"
;

static const unsigned char rfc8259Embedded007iNumberTooBigNegIntJson[] =
    "[-123123123123123123123123123123]"
;

static const unsigned char rfc8259Embedded008iNumberTooBigPosIntJson[] =
    "[100000000000000000000]"
;

static const unsigned char rfc8259Embedded009iNumberVeryBigNegativeIntJson[] =
    "[-237462374673276894279832749832423479823246327846]"
;

static const unsigned char rfc8259Embedded010iObjectKeyLone2ndSurrogateJson[] =
    "{\"\\uDFAA\":0}"
;

static const unsigned char rfc8259Embedded011iString1stSurrogateBut2ndMissingJson[] =
    "[\"\\uDADA\"]"
;

static const unsigned char rfc8259Embedded012iString1stValidSurrogate2ndInvalidJson[] =
    "[\"\\uD888\\u1234\"]"
;

static const unsigned char rfc8259Embedded013iStringUTF16LEWithBOMJson[] =
    "\377\376[\000\"\000\351\000\"\000]\000"
;

static const unsigned char rfc8259Embedded014iStringUTF8InvalidSequenceJson[] =
    "[\"\346\227\245\321\210\372\"]"
;

static const unsigned char rfc8259Embedded015iStringUTF8SurrogateUD800Json[] =
    "[\"\355\240\200\"]"
;

static const unsigned char rfc8259Embedded016iStringIncompleteSurrogateAndEscapeValidJson[] =
    "[\"\\uD800\\n\"]"
;

static const unsigned char rfc8259Embedded017iStringIncompleteSurrogatePairJson[] =
    "[\"\\uDd1ea\"]"
;

static const unsigned char rfc8259Embedded018iStringIncompleteSurrogatesEscapeValidJson[] =
    "[\"\\uD800\\uD800\\n\"]"
;

static const unsigned char rfc8259Embedded019iStringInvalidLonelySurrogateJson[] =
    "[\"\\ud800\"]"
;

static const unsigned char rfc8259Embedded020iStringInvalidSurrogateJson[] =
    "[\"\\ud800abc\"]"
;

static const unsigned char rfc8259Embedded021iStringInvalidUtf8Json[] =
    "[\"\377\"]"
;

static const unsigned char rfc8259Embedded022iStringInvertedSurrogatesU1D11EJson[] =
    "[\"\\uDd1e\\uD834\"]"
;

static const unsigned char rfc8259Embedded023iStringIsoLatin1Json[] =
    "[\"\351\"]"
;

static const unsigned char rfc8259Embedded024iStringLoneSecondSurrogateJson[] =
    "[\"\\uDFAA\"]"
;

static const unsigned char rfc8259Embedded025iStringLoneUtf8ContinuationByteJson[] =
    "[\"\201\"]"
;

static const unsigned char rfc8259Embedded026iStringNotInUnicodeRangeJson[] =
    "[\"\364\277\277\277\"]"
;

static const unsigned char rfc8259Embedded027iStringOverlongSequence2BytesJson[] =
    "[\"\300\257\"]"
;

static const unsigned char rfc8259Embedded028iStringOverlongSequence6BytesJson[] =
    "[\"\374\203\277\277\277\277\"]"
;

static const unsigned char rfc8259Embedded029iStringOverlongSequence6BytesNullJson[] =
    "[\"\374\200\200\200\200\200\"]"
;

static const unsigned char rfc8259Embedded030iStringTruncatedUtf8Json[] =
    "[\"\340\377\"]"
;

static const unsigned char rfc8259Embedded031iStringUtf16BENoBOMJson[] =
    "\000[\000\"\000\351\000\"\000]"
;

static const unsigned char rfc8259Embedded032iStringUtf16LENoBOMJson[] =
    "[\000\"\000\351\000\"\000]\000"
;

static const unsigned char rfc8259Embedded033iStructureUTF8BOMEmptyObjectJson[] =
    "\357\273\277{}"
;

static const unsigned char rfc8259Embedded034nArray1TrueWithoutCommaJson[] =
    "[1 true]"
;

static const unsigned char rfc8259Embedded035nArrayAInvalidUtf8Json[] =
    "[a\345]"
;

static const unsigned char rfc8259Embedded036nArrayColonInsteadOfCommaJson[] =
    "[\"\": 1]"
;

static const unsigned char rfc8259Embedded037nArrayCommaAfterCloseJson[] =
    "[\"\"],"
;

static const unsigned char rfc8259Embedded038nArrayCommaAndNumberJson[] =
    "[,1]"
;

static const unsigned char rfc8259Embedded039nArrayDoubleCommaJson[] =
    "[1,,2]"
;

static const unsigned char rfc8259Embedded040nArrayDoubleExtraCommaJson[] =
    "[\"x\",,]"
;

static const unsigned char rfc8259Embedded041nArrayExtraCloseJson[] =
    "[\"x\"]]"
;

static const unsigned char rfc8259Embedded042nArrayExtraCommaJson[] =
    "[\"\",]"
;

static const unsigned char rfc8259Embedded043nArrayIncompleteJson[] =
    "[\"x\""
;

static const unsigned char rfc8259Embedded044nArrayIncompleteInvalidValueJson[] =
    "[x"
;

static const unsigned char rfc8259Embedded045nArrayInnerArrayNoCommaJson[] =
    "[3[4]]"
;

static const unsigned char rfc8259Embedded046nArrayInvalidUtf8Json[] =
    "[\377]"
;

static const unsigned char rfc8259Embedded047nArrayItemsSeparatedBySemicolonJson[] =
    "[1:2]"
;

static const unsigned char rfc8259Embedded048nArrayJustCommaJson[] =
    "[,]"
;

static const unsigned char rfc8259Embedded049nArrayJustMinusJson[] =
    "[-]"
;

static const unsigned char rfc8259Embedded050nArrayMissingValueJson[] =
    "[   , \"\"]"
;

static const unsigned char rfc8259Embedded051nArrayNewlinesUnclosedJson[] =
    "[\"a\",\n4\n,1,"
;

static const unsigned char rfc8259Embedded052nArrayNumberAndCommaJson[] =
    "[1,]"
;

static const unsigned char rfc8259Embedded053nArrayNumberAndSeveralCommasJson[] =
    "[1,,]"
;

static const unsigned char rfc8259Embedded054nArraySpacesVerticalTabFormfeedJson[] =
    "[\"\013a\"\\f]"
;

static const unsigned char rfc8259Embedded055nArrayStarInsideJson[] =
    "[*]"
;

static const unsigned char rfc8259Embedded056nArrayUnclosedJson[] =
    "[\"\""
;

static const unsigned char rfc8259Embedded057nArrayUnclosedTrailingCommaJson[] =
    "[1,"
;

static const unsigned char rfc8259Embedded058nArrayUnclosedWithNewLinesJson[] =
    "[1,\n1\n,1"
;

static const unsigned char rfc8259Embedded059nArrayUnclosedWithObjectInsideJson[] =
    "[{}"
;

static const unsigned char rfc8259Embedded060nIncompleteFalseJson[] =
    "[fals]"
;

static const unsigned char rfc8259Embedded061nIncompleteNullJson[] =
    "[nul]"
;

static const unsigned char rfc8259Embedded062nIncompleteTrueJson[] =
    "[tru]"
;

static const unsigned char rfc8259Embedded063nMultidigitNumberThen00Json[] =
    "123\000"
;

static const unsigned char rfc8259Embedded064nNumberJson[] =
    "[++1234]"
;

static const unsigned char rfc8259Embedded065nNumber1Json[] =
    "[+1]"
;

static const unsigned char rfc8259Embedded066nNumberInfJson[] =
    "[+Inf]"
;

static const unsigned char rfc8259Embedded067nNumber01Json[] =
    "[-01]"
;

static const unsigned char rfc8259Embedded068nNumber10Json[] =
    "[-1.0.]"
;

static const unsigned char rfc8259Embedded069nNumber2Json[] =
    "[-2.]"
;

static const unsigned char rfc8259Embedded070nNumberNaNJson[] =
    "[-NaN]"
;

static const unsigned char rfc8259Embedded071nNumber1Json[] =
    "[.-1]"
;

static const unsigned char rfc8259Embedded072nNumber2e3Json[] =
    "[.2e-3]"
;

static const unsigned char rfc8259Embedded073nNumber012Json[] =
    "[0.1.2]"
;

static const unsigned char rfc8259Embedded074nNumber03eJson[] =
    "[0.3e+]"
;

static const unsigned char rfc8259Embedded075nNumber03eJson[] =
    "[0.3e]"
;

static const unsigned char rfc8259Embedded076nNumber0E1Json[] =
    "[0.e1]"
;

static const unsigned char rfc8259Embedded077nNumber0CapitalEJson[] =
    "[0E+]"
;

static const unsigned char rfc8259Embedded078nNumber0CapitalEJson[] =
    "[0E]"
;

static const unsigned char rfc8259Embedded079nNumber0eJson[] =
    "[0e+]"
;

static const unsigned char rfc8259Embedded080nNumber0eJson[] =
    "[0e]"
;

static const unsigned char rfc8259Embedded081nNumber10eJson[] =
    "[1.0e+]"
;

static const unsigned char rfc8259Embedded082nNumber10eJson[] =
    "[1.0e-]"
;

static const unsigned char rfc8259Embedded083nNumber10eJson[] =
    "[1.0e]"
;

static const unsigned char rfc8259Embedded084nNumber1000Json[] =
    "[1 000.0]"
;

static const unsigned char rfc8259Embedded085nNumber1eE2Json[] =
    "[1eE2]"
;

static const unsigned char rfc8259Embedded086nNumber2E3Json[] =
    "[2.e+3]"
;

static const unsigned char rfc8259Embedded087nNumber2E3Json[] =
    "[2.e-3]"
;

static const unsigned char rfc8259Embedded088nNumber2E3Json[] =
    "[2.e3]"
;

static const unsigned char rfc8259Embedded089nNumber9EJson[] =
    "[9.e+]"
;

static const unsigned char rfc8259Embedded090nNumberInfJson[] =
    "[Inf]"
;

static const unsigned char rfc8259Embedded091nNumberNaNJson[] =
    "[NaN]"
;

static const unsigned char rfc8259Embedded092nNumberUFF11FullwidthDigitOneJson[] =
    "[\357\274\221]"
;

static const unsigned char rfc8259Embedded093nNumberExpressionJson[] =
    "[1+2]"
;

static const unsigned char rfc8259Embedded094nNumberHex1DigitJson[] =
    "[0x1]"
;

static const unsigned char rfc8259Embedded095nNumberHex2DigitsJson[] =
    "[0x42]"
;

static const unsigned char rfc8259Embedded096nNumberInfinityJson[] =
    "[Infinity]"
;

static const unsigned char rfc8259Embedded097nNumberInvalidJson[] =
    "[0e+-1]"
;

static const unsigned char rfc8259Embedded098nNumberInvalidNegativeRealJson[] =
    "[-123.123foo]"
;

static const unsigned char rfc8259Embedded099nNumberInvalidUtf8InBiggerIntJson[] =
    "[123\345]"
;

static const unsigned char rfc8259Embedded100nNumberInvalidUtf8InExponentJson[] =
    "[1e1\345]"
;

static const unsigned char rfc8259Embedded101nNumberInvalidUtf8InIntJson[] =
    "[0\345]\n"
;

static const unsigned char rfc8259Embedded102nNumberMinusInfinityJson[] =
    "[-Infinity]"
;

static const unsigned char rfc8259Embedded103nNumberMinusSignWithTrailingGarbageJson[] =
    "[-foo]"
;

static const unsigned char rfc8259Embedded104nNumberMinusSpace1Json[] =
    "[- 1]"
;

static const unsigned char rfc8259Embedded105nNumberNegIntStartingWithZeroJson[] =
    "[-012]"
;

static const unsigned char rfc8259Embedded106nNumberNegRealWithoutIntPartJson[] =
    "[-.123]"
;

static const unsigned char rfc8259Embedded107nNumberNegWithGarbageAtEndJson[] =
    "[-1x]"
;

static const unsigned char rfc8259Embedded108nNumberRealGarbageAfterEJson[] =
    "[1ea]"
;

static const unsigned char rfc8259Embedded109nNumberRealWithInvalidUtf8AfterEJson[] =
    "[1e\345]"
;

static const unsigned char rfc8259Embedded110nNumberRealWithoutFractionalPartJson[] =
    "[1.]"
;

static const unsigned char rfc8259Embedded111nNumberStartingWithDotJson[] =
    "[.123]"
;

static const unsigned char rfc8259Embedded112nNumberWithAlphaJson[] =
    "[1.2a-3]"
;

static const unsigned char rfc8259Embedded113nNumberWithAlphaCharJson[] =
    "[1.8011670033376514H-308]"
;

static const unsigned char rfc8259Embedded114nNumberWithLeadingZeroJson[] =
    "[012]"
;

static const unsigned char rfc8259Embedded115nObjectBadValueJson[] =
    "[\"x\", truth]"
;

static const unsigned char rfc8259Embedded116nObjectBracketKeyJson[] =
    "{[: \"x\"}\n"
;

static const unsigned char rfc8259Embedded117nObjectCommaInsteadOfColonJson[] =
    "{\"x\", null}"
;

static const unsigned char rfc8259Embedded118nObjectDoubleColonJson[] =
    "{\"x\"::\"b\"}"
;

static const unsigned char rfc8259Embedded119nObjectEmojiJson[] =
    "{\360\237\207\250\360\237\207\255}"
;

static const unsigned char rfc8259Embedded120nObjectGarbageAtEndJson[] =
    "{\"a\":\"a\" 123}"
;

static const unsigned char rfc8259Embedded121nObjectKeyWithSingleQuotesJson[] =
    "{key: 'value'}"
;

static const unsigned char rfc8259Embedded122nObjectLoneContinuationByteInKeyAndTrailingCommaJson[] =
    "{\"\271\":\"0\",}"
;

static const unsigned char rfc8259Embedded123nObjectMissingColonJson[] =
    "{\"a\" b}"
;

static const unsigned char rfc8259Embedded124nObjectMissingKeyJson[] =
    "{:\"b\"}"
;

static const unsigned char rfc8259Embedded125nObjectMissingSemicolonJson[] =
    "{\"a\" \"b\"}"
;

static const unsigned char rfc8259Embedded126nObjectMissingValueJson[] =
    "{\"a\":"
;

static const unsigned char rfc8259Embedded127nObjectNoColonJson[] =
    "{\"a\""
;

static const unsigned char rfc8259Embedded128nObjectNonStringKeyJson[] =
    "{1:1}"
;

static const unsigned char rfc8259Embedded129nObjectNonStringKeyButHugeNumberInsteadJson[] =
    "{9999E9999:1}"
;

static const unsigned char rfc8259Embedded130nObjectRepeatedNullNullJson[] =
    "{null:null,null:null}"
;

static const unsigned char rfc8259Embedded131nObjectSeveralTrailingCommasJson[] =
    "{\"id\":0,,,,,}"
;

static const unsigned char rfc8259Embedded132nObjectSingleQuoteJson[] =
    "{'a':0}"
;

static const unsigned char rfc8259Embedded133nObjectTrailingCommaJson[] =
    "{\"id\":0,}"
;

static const unsigned char rfc8259Embedded134nObjectTrailingCommentJson[] =
    "{\"a\":\"b\"}/**/"
;

static const unsigned char rfc8259Embedded135nObjectTrailingCommentOpenJson[] =
    "{\"a\":\"b\"}/**//"
;

static const unsigned char rfc8259Embedded136nObjectTrailingCommentSlashOpenJson[] =
    "{\"a\":\"b\"}//"
;

static const unsigned char rfc8259Embedded137nObjectTrailingCommentSlashOpenIncompleteJson[] =
    "{\"a\":\"b\"}/"
;

static const unsigned char rfc8259Embedded138nObjectTwoCommasInARowJson[] =
    "{\"a\":\"b\",,\"c\":\"d\"}"
;

static const unsigned char rfc8259Embedded139nObjectUnquotedKeyJson[] =
    "{a: \"b\"}"
;

static const unsigned char rfc8259Embedded140nObjectUnterminatedValueJson[] =
    "{\"a\":\"a"
;

static const unsigned char rfc8259Embedded141nObjectWithSingleStringJson[] =
    "{ \"foo\" : \"bar\", \"a\" }"
;

static const unsigned char rfc8259Embedded142nObjectWithTrailingGarbageJson[] =
    "{\"a\":\"b\"}#"
;

static const unsigned char rfc8259Embedded143nSingleSpaceJson[] =
    " "
;

static const unsigned char rfc8259Embedded144nString1SurrogateThenEscapeJson[] =
    "[\"\\uD800\\\"]"
;

static const unsigned char rfc8259Embedded145nString1SurrogateThenEscapeUJson[] =
    "[\"\\uD800\\u\"]"
;

static const unsigned char rfc8259Embedded146nString1SurrogateThenEscapeU1Json[] =
    "[\"\\uD800\\u1\"]"
;

static const unsigned char rfc8259Embedded147nString1SurrogateThenEscapeU1xJson[] =
    "[\"\\uD800\\u1x\"]"
;

static const unsigned char rfc8259Embedded148nStringAccentuatedCharNoQuotesJson[] =
    "[\303\251]"
;

static const unsigned char rfc8259Embedded149nStringBackslash00Json[] =
    "[\"\\\000\"]"
;

static const unsigned char rfc8259Embedded150nStringEscapeXJson[] =
    "[\"\\x00\"]"
;

static const unsigned char rfc8259Embedded151nStringEscapedBackslashBadJson[] =
    "[\"\\\\\\\"]"
;

static const unsigned char rfc8259Embedded152nStringEscapedCtrlCharTabJson[] =
    "[\"\\\t\"]"
;

static const unsigned char rfc8259Embedded153nStringEscapedEmojiJson[] =
    "[\"\\\360\237\214\200\"]"
;

static const unsigned char rfc8259Embedded154nStringIncompleteEscapeJson[] =
    "[\"\\\"]"
;

static const unsigned char rfc8259Embedded155nStringIncompleteEscapedCharacterJson[] =
    "[\"\\u00A\"]"
;

static const unsigned char rfc8259Embedded156nStringIncompleteSurrogateJson[] =
    "[\"\\uD834\\uDd\"]"
;

static const unsigned char rfc8259Embedded157nStringIncompleteSurrogateEscapeInvalidJson[] =
    "[\"\\uD800\\uD800\\x\"]"
;

static const unsigned char rfc8259Embedded158nStringInvalidUtf8InEscapeJson[] =
    "[\"\\u\345\"]"
;

static const unsigned char rfc8259Embedded159nStringInvalidBackslashEscJson[] =
    "[\"\\a\"]"
;

static const unsigned char rfc8259Embedded160nStringInvalidUnicodeEscapeJson[] =
    "[\"\\uqqqq\"]"
;

static const unsigned char rfc8259Embedded161nStringInvalidUtf8AfterEscapeJson[] =
    "[\"\\\345\"]"
;

static const unsigned char rfc8259Embedded162nStringLeadingUescapedThinspaceJson[] =
    "[\\u0020\"asd\"]"
;

static const unsigned char rfc8259Embedded163nStringNoQuotesWithBadEscapeJson[] =
    "[\\n]"
;

static const unsigned char rfc8259Embedded164nStringSingleDoublequoteJson[] =
    "\""
;

static const unsigned char rfc8259Embedded165nStringSingleQuoteJson[] =
    "['single quote']"
;

static const unsigned char rfc8259Embedded166nStringSingleStringNoDoubleQuotesJson[] =
    "abc"
;

static const unsigned char rfc8259Embedded167nStringStartEscapeUnclosedJson[] =
    "[\"\\"
;

static const unsigned char rfc8259Embedded168nStringUnescapedCtrlCharJson[] =
    "[\"a\000a\"]"
;

static const unsigned char rfc8259Embedded169nStringUnescapedNewlineJson[] =
    "[\"new\nline\"]"
;

static const unsigned char rfc8259Embedded170nStringUnescapedTabJson[] =
    "[\"\t\"]"
;

static const unsigned char rfc8259Embedded171nStringUnicodeCapitalUJson[] =
    "\"\\UA66D\""
;

static const unsigned char rfc8259Embedded172nStringWithTrailingGarbageJson[] =
    "\"\"x"
;

static const unsigned char rfc8259Embedded173nStructureU2060WordJoinedJson[] =
    "[\342\201\240]"
;

static const unsigned char rfc8259Embedded174nStructureUTF8BOMNoDataJson[] =
    "\357\273\277"
;

static const unsigned char rfc8259Embedded175nStructureAngleBracketJson[] =
    "<.>"
;

static const unsigned char rfc8259Embedded176nStructureAngleBracketNullJson[] =
    "[<null>]"
;

static const unsigned char rfc8259Embedded177nStructureArrayTrailingGarbageJson[] =
    "[1]x"
;

static const unsigned char rfc8259Embedded178nStructureArrayWithExtraArrayCloseJson[] =
    "[1]]"
;

static const unsigned char rfc8259Embedded179nStructureArrayWithUnclosedStringJson[] =
    "[\"asd]"
;

static const unsigned char rfc8259Embedded180nStructureAsciiUnicodeIdentifierJson[] =
    "a\303\245"
;

static const unsigned char rfc8259Embedded181nStructureCapitalizedTrueJson[] =
    "[True]"
;

static const unsigned char rfc8259Embedded182nStructureCloseUnopenedArrayJson[] =
    "1]"
;

static const unsigned char rfc8259Embedded183nStructureCommaInsteadOfClosingBraceJson[] =
    "{\"x\": true,"
;

static const unsigned char rfc8259Embedded184nStructureDoubleArrayJson[] =
    "[][]"
;

static const unsigned char rfc8259Embedded185nStructureEndArrayJson[] =
    "]"
;

static const unsigned char rfc8259Embedded186nStructureIncompleteUTF8BOMJson[] =
    "\357\273{}"
;

static const unsigned char rfc8259Embedded187nStructureLoneInvalidUtf8Json[] =
    "\345"
;

static const unsigned char rfc8259Embedded188nStructureLoneOpenBracketJson[] =
    "["
;

static const unsigned char rfc8259Embedded189nStructureNoDataJson[] =
    ""
;

static const unsigned char rfc8259Embedded190nStructureNullByteOutsideStringJson[] =
    "[\000]"
;

static const unsigned char rfc8259Embedded191nStructureNumberWithTrailingGarbageJson[] =
    "2@"
;

static const unsigned char rfc8259Embedded192nStructureObjectFollowedByClosingObjectJson[] =
    "{}}"
;

static const unsigned char rfc8259Embedded193nStructureObjectUnclosedNoValueJson[] =
    "{\"\":"
;

static const unsigned char rfc8259Embedded194nStructureObjectWithCommentJson[] =
    "{\"a\":/*comment*/\"b\"}"
;

static const unsigned char rfc8259Embedded195nStructureObjectWithTrailingGarbageJson[] =
    "{\"a\": true} \"x\""
;

static const unsigned char rfc8259Embedded196nStructureOpenArrayApostropheJson[] =
    "['"
;

static const unsigned char rfc8259Embedded197nStructureOpenArrayCommaJson[] =
    "[,"
;

static const unsigned char rfc8259Embedded198nStructureOpenArrayOpenObjectJson[] =
    "[{"
;

static const unsigned char rfc8259Embedded199nStructureOpenArrayOpenStringJson[] =
    "[\"a"
;

static const unsigned char rfc8259Embedded200nStructureOpenArrayStringJson[] =
    "[\"a\""
;

static const unsigned char rfc8259Embedded201nStructureOpenObjectJson[] =
    "{"
;

static const unsigned char rfc8259Embedded202nStructureOpenObjectCloseArrayJson[] =
    "{]"
;

static const unsigned char rfc8259Embedded203nStructureOpenObjectCommaJson[] =
    "{,"
;

static const unsigned char rfc8259Embedded204nStructureOpenObjectOpenArrayJson[] =
    "{["
;

static const unsigned char rfc8259Embedded205nStructureOpenObjectOpenStringJson[] =
    "{\"a"
;

static const unsigned char rfc8259Embedded206nStructureOpenObjectStringWithApostrophesJson[] =
    "{'a'"
;

static const unsigned char rfc8259Embedded207nStructureOpenOpenJson[] =
    "[\"\\{[\"\\{[\"\\{[\"\\{"
;

static const unsigned char rfc8259Embedded208nStructureSingleEacuteJson[] =
    "\351"
;

static const unsigned char rfc8259Embedded209nStructureSingleStarJson[] =
    "*"
;

static const unsigned char rfc8259Embedded210nStructureTrailingJson[] =
    "{\"a\":\"b\"}#{}"
;

static const unsigned char rfc8259Embedded211nStructureUescapedLFBeforeStringJson[] =
    "[\\u000A\"\"]"
;

static const unsigned char rfc8259Embedded212nStructureUnclosedArrayJson[] =
    "[1"
;

static const unsigned char rfc8259Embedded213nStructureUnclosedArrayPartialNullJson[] =
    "[ false, nul"
;

static const unsigned char rfc8259Embedded214nStructureUnclosedArrayUnfinishedFalseJson[] =
    "[ true, fals"
;

static const unsigned char rfc8259Embedded215nStructureUnclosedArrayUnfinishedTrueJson[] =
    "[ false, tru"
;

static const unsigned char rfc8259Embedded216nStructureUnclosedObjectJson[] =
    "{\"asd\":\"asd\""
;

static const unsigned char rfc8259Embedded217nStructureUnicodeIdentifierJson[] =
    "\303\245"
;

static const unsigned char rfc8259Embedded218nStructureWhitespaceU2060WordJoinerJson[] =
    "[\342\201\240]"
;

static const unsigned char rfc8259Embedded219nStructureWhitespaceFormfeedJson[] =
    "[\f]"
;

static const unsigned char rfc8259Embedded220y1Json[] =
    "{\"emoji\":\"\360\237\230\200\"}"
;

static const unsigned char rfc8259Embedded221y2Json[] =
    "{\"rare\":\"\360\240\200\200\"}"
;

static const unsigned char rfc8259Embedded222y3Json[] =
    "{\"mahjong\":\"\360\237\200\204\"}"
;

static const unsigned char rfc8259Embedded223yArrayArraysWithSpacesJson[] =
    "[[]   ]"
;

static const unsigned char rfc8259Embedded224yArrayEmptyStringJson[] =
    "[\"\"]"
;

static const unsigned char rfc8259Embedded225yArrayEmptyJson[] =
    "[]"
;

static const unsigned char rfc8259Embedded226yArrayEndingWithNewlineJson[] =
    "[\"a\"]"
;

static const unsigned char rfc8259Embedded227yArrayFalseJson[] =
    "[false]"
;

static const unsigned char rfc8259Embedded228yArrayHeterogeneousJson[] =
    "[null, 1, \"1\", {}]"
;

static const unsigned char rfc8259Embedded229yArrayNestingJson[] =
    "[[], [], [], [], [], [], [], [], [], []]\n"
;

static const unsigned char rfc8259Embedded230yArrayNullJson[] =
    "[null]"
;

static const unsigned char rfc8259Embedded231yArrayWith1AndNewlineJson[] =
    "[1\n]"
;

static const unsigned char rfc8259Embedded232yArrayWithLeadingSpaceJson[] =
    " [1]"
;

static const unsigned char rfc8259Embedded233yArrayWithSeveralNullJson[] =
    "[1,null,null,null,2]"
;

static const unsigned char rfc8259Embedded234yArrayWithTrailingSpaceJson[] =
    "[2] "
;

static const unsigned char rfc8259Embedded235yNumberJson[] =
    "[123e65]"
;

static const unsigned char rfc8259Embedded236yNumber0e1Json[] =
    "[0e+1]"
;

static const unsigned char rfc8259Embedded237yNumber0e1Json[] =
    "[0e1]"
;

static const unsigned char rfc8259Embedded238yNumberAfterSpaceJson[] =
    "[ 4]"
;

static const unsigned char rfc8259Embedded239yNumberDoubleCloseToZeroJson[] =
    "[-0.000000000000000000000000000000000000000000000000000000000000000000000000000001]\n"
;

static const unsigned char rfc8259Embedded240yNumberIntWithExpJson[] =
    "[20e1]"
;

static const unsigned char rfc8259Embedded241yNumberMinusZeroJson[] =
    "[-0]"
;

static const unsigned char rfc8259Embedded242yNumberNegativeIntJson[] =
    "[-123]"
;

static const unsigned char rfc8259Embedded243yNumberNegativeOneJson[] =
    "[-1]"
;

static const unsigned char rfc8259Embedded244yNumberNegativeZeroJson[] =
    "[-0]"
;

static const unsigned char rfc8259Embedded245yNumberRealCapitalEJson[] =
    "[1E22]"
;

static const unsigned char rfc8259Embedded246yNumberRealCapitalENegExpJson[] =
    "[1E-2]"
;

static const unsigned char rfc8259Embedded247yNumberRealCapitalEPosExpJson[] =
    "[1E+2]"
;

static const unsigned char rfc8259Embedded248yNumberRealExponentJson[] =
    "[123e45]"
;

static const unsigned char rfc8259Embedded249yNumberRealFractionExponentJson[] =
    "[123.456e78]"
;

static const unsigned char rfc8259Embedded250yNumberRealNegExpJson[] =
    "[1e-2]"
;

static const unsigned char rfc8259Embedded251yNumberRealPosExponentJson[] =
    "[1e+2]"
;

static const unsigned char rfc8259Embedded252yNumberSimpleIntJson[] =
    "[123]"
;

static const unsigned char rfc8259Embedded253yNumberSimpleRealJson[] =
    "[123.456789]"
;

static const unsigned char rfc8259Embedded254yObjectJson[] =
    "{\"asd\":\"sdf\", \"dfg\":\"fgh\"}"
;

static const unsigned char rfc8259Embedded255yObjectBasicJson[] =
    "{\"asd\":\"sdf\"}"
;

static const unsigned char rfc8259Embedded256yObjectDuplicatedKeyJson[] =
    "{\"a\":\"b\",\"a\":\"c\"}"
;

static const unsigned char rfc8259Embedded257yObjectDuplicatedKeyAndValueJson[] =
    "{\"a\":\"b\",\"a\":\"b\"}"
;

static const unsigned char rfc8259Embedded258yObjectEmptyJson[] =
    "{}"
;

static const unsigned char rfc8259Embedded259yObjectEmptyKeyJson[] =
    "{\"\":0}"
;

static const unsigned char rfc8259Embedded260yObjectEscapedNullInKeyJson[] =
    "{\"foo\\u0000bar\": 42}"
;

static const unsigned char rfc8259Embedded261yObjectExtremeNumbersJson[] =
    "{ \"min\": -1.0e+28, \"max\": 1.0e+28 }"
;

static const unsigned char rfc8259Embedded262yObjectLongStringsJson[] =
    "{\"x\":[{\"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}], \"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    "x\"}"
;

static const unsigned char rfc8259Embedded263yObjectSimpleJson[] =
    "{\"a\":[]}"
;

static const unsigned char rfc8259Embedded264yObjectStringUnicodeJson[] =
    "{\"title\":\"\\u041f\\u043e\\u043b\\u0442\\u043e\\u0440\\u0430 \\u0417\\u0435\\u043c\\u043b\\u0435\\u043a\\u043e\\"
    "u043f\\u0430\" }"
;

static const unsigned char rfc8259Embedded265yObjectWithNewlinesJson[] =
    "{\n\"a\": \"b\"\n}"
;

static const unsigned char rfc8259Embedded266yString123BytesUTF8SequencesJson[] =
    "[\"\\u0060\\u012a\\u12AB\"]"
;

static const unsigned char rfc8259Embedded267yStringAcceptedSurrogatePairJson[] =
    "[\"\\uD801\\udc37\"]"
;

static const unsigned char rfc8259Embedded268yStringAcceptedSurrogatePairsJson[] =
    "[\"\\ud83d\\ude39\\ud83d\\udc8d\"]"
;

static const unsigned char rfc8259Embedded269yStringAllowedEscapesJson[] =
    "[\"\\\"\\\\\\/\\b\\f\\n\\r\\t\"]"
;

static const unsigned char rfc8259Embedded270yStringBackslashAndUEscapedZeroJson[] =
    "[\"\\\\u0000\"]"
;

static const unsigned char rfc8259Embedded271yStringBackslashDoublequotesJson[] =
    "[\"\\\"\"]"
;

static const unsigned char rfc8259Embedded272yStringCommentsJson[] =
    "[\"a/*b*/c/*d//e\"]"
;

static const unsigned char rfc8259Embedded273yStringDoubleEscapeAJson[] =
    "[\"\\\\a\"]"
;

static const unsigned char rfc8259Embedded274yStringDoubleEscapeNJson[] =
    "[\"\\\\n\"]"
;

static const unsigned char rfc8259Embedded275yStringEscapedControlCharacterJson[] =
    "[\"\\u0012\"]"
;

static const unsigned char rfc8259Embedded276yStringEscapedNoncharacterJson[] =
    "[\"\\uFFFF\"]"
;

static const unsigned char rfc8259Embedded277yStringInArrayJson[] =
    "[\"asd\"]"
;

static const unsigned char rfc8259Embedded278yStringInArrayWithLeadingSpaceJson[] =
    "[ \"asd\"]"
;

static const unsigned char rfc8259Embedded279yStringLastSurrogates1And2Json[] =
    "[\"\\uDBFF\\uDFFF\"]"
;

static const unsigned char rfc8259Embedded280yStringNbspUescapedJson[] =
    "[\"new\\u00A0line\"]"
;

static const unsigned char rfc8259Embedded281yStringNonCharacterInUTF8U10FFFFJson[] =
    "[\"\364\217\277\277\"]"
;

static const unsigned char rfc8259Embedded282yStringNonCharacterInUTF8UFFFFJson[] =
    "[\"\357\277\277\"]"
;

static const unsigned char rfc8259Embedded283yStringNullEscapeJson[] =
    "[\"\\u0000\"]"
;

static const unsigned char rfc8259Embedded284yStringOneByteUtf8Json[] =
    "[\"\\u002c\"]"
;

static const unsigned char rfc8259Embedded285yStringPiJson[] =
    "[\"\317\200\"]"
;

static const unsigned char rfc8259Embedded286yStringReservedCharacterInUTF8U1BFFFJson[] =
    "[\"\360\233\277\277\"]"
;

static const unsigned char rfc8259Embedded287yStringSimpleAsciiJson[] =
    "[\"asd \"]"
;

static const unsigned char rfc8259Embedded288yStringSpaceJson[] =
    "\" \""
;

static const unsigned char rfc8259Embedded289yStringSurrogatesU1D11EMUSICALSYMBOLGCLEFJson[] =
    "[\"\\uD834\\uDd1e\"]"
;

static const unsigned char rfc8259Embedded290yStringThreeByteUtf8Json[] =
    "[\"\\u0821\"]"
;

static const unsigned char rfc8259Embedded291yStringTwoByteUtf8Json[] =
    "[\"\\u0123\"]"
;

static const unsigned char rfc8259Embedded292yStringU2028LineSepJson[] =
    "[\"\342\200\250\"]"
;

static const unsigned char rfc8259Embedded293yStringU2029ParSepJson[] =
    "[\"\342\200\251\"]"
;

static const unsigned char rfc8259Embedded294yStringUEscapeJson[] =
    "[\"\\u0061\\u30af\\u30EA\\u30b9\"]"
;

static const unsigned char rfc8259Embedded295yStringUescapedNewlineJson[] =
    "[\"new\\u000Aline\"]"
;

static const unsigned char rfc8259Embedded296yStringUnescapedCharDeleteJson[] =
    "[\"\177\"]"
;

static const unsigned char rfc8259Embedded297yStringUnicodeJson[] =
    "[\"\\uA66D\"]"
;

static const unsigned char rfc8259Embedded298yStringUnicodeEscapedBackslashJson[] =
    "[\"\\u005C\"]"
;

static const unsigned char rfc8259Embedded299yStringUnicode2Json[] =
    "[\"\342\215\202\343\210\264\342\215\202\"]"
;

static const unsigned char rfc8259Embedded300yStringUnicodeU10FFFENoncharJson[] =
    "[\"\\uDBFF\\uDFFE\"]"
;

static const unsigned char rfc8259Embedded301yStringUnicodeU1FFFENoncharJson[] =
    "[\"\\uD83F\\uDFFE\"]"
;

static const unsigned char rfc8259Embedded302yStringUnicodeU200BZEROWIDTHSPACEJson[] =
    "[\"\\u200B\"]"
;

static const unsigned char rfc8259Embedded303yStringUnicodeU2064InvisiblePlusJson[] =
    "[\"\\u2064\"]"
;

static const unsigned char rfc8259Embedded304yStringUnicodeUFDD0NoncharJson[] =
    "[\"\\uFDD0\"]"
;

static const unsigned char rfc8259Embedded305yStringUnicodeUFFFENoncharJson[] =
    "[\"\\uFFFE\"]"
;

static const unsigned char rfc8259Embedded306yStringUnicodeEscapedDoubleQuoteJson[] =
    "[\"\\u0022\"]"
;

static const unsigned char rfc8259Embedded307yStringUtf8Json[] =
    "[\"\342\202\254\360\235\204\236\"]"
;

static const unsigned char rfc8259Embedded308yStringWithDelCharacterJson[] =
    "[\"a\177a\"]"
;

static const unsigned char rfc8259Embedded309yStructureLonelyFalseJson[] =
    "false"
;

static const unsigned char rfc8259Embedded310yStructureLonelyIntJson[] =
    "42"
;

static const unsigned char rfc8259Embedded311yStructureLonelyNegativeRealJson[] =
    "-0.1"
;

static const unsigned char rfc8259Embedded312yStructureLonelyNullJson[] =
    "null"
;

static const unsigned char rfc8259Embedded313yStructureLonelyStringJson[] =
    "\"asd\""
;

static const unsigned char rfc8259Embedded314yStructureLonelyTrueJson[] =
    "true"
;

static const unsigned char rfc8259Embedded315yStructureStringEmptyJson[] =
    "\"\""
;

static const unsigned char rfc8259Embedded316yStructureTrailingNewlineJson[] =
    "[\"a\"]\n"
;

static const unsigned char rfc8259Embedded317yStructureTrueInArrayJson[] =
    "[true]"
;

static const unsigned char rfc8259Embedded318yStructureWhitespaceArrayJson[] =
    " [] "
;

const rfc8259EmbeddedFile_t gRfc8259EmbeddedFiles[] = {
	{"i_number_double_huge_neg_exp.json", rfc8259Embedded000iNumberDoubleHugeNegExpJson, 14U},
	{"i_number_huge_exp.json", rfc8259Embedded001iNumberHugeExpJson, 137U},
	{"i_number_neg_int_huge_exp.json", rfc8259Embedded002iNumberNegIntHugeExpJson, 10U},
	{"i_number_pos_double_huge_exp.json", rfc8259Embedded003iNumberPosDoubleHugeExpJson, 11U},
	{"i_number_real_neg_overflow.json", rfc8259Embedded004iNumberRealNegOverflowJson, 16U},
	{"i_number_real_pos_overflow.json", rfc8259Embedded005iNumberRealPosOverflowJson, 15U},
	{"i_number_real_underflow.json", rfc8259Embedded006iNumberRealUnderflowJson, 15U},
	{"i_number_too_big_neg_int.json", rfc8259Embedded007iNumberTooBigNegIntJson, 33U},
	{"i_number_too_big_pos_int.json", rfc8259Embedded008iNumberTooBigPosIntJson, 23U},
	{"i_number_very_big_negative_int.json", rfc8259Embedded009iNumberVeryBigNegativeIntJson, 51U},
	{"i_object_key_lone_2nd_surrogate.json", rfc8259Embedded010iObjectKeyLone2ndSurrogateJson, 12U},
	{"i_string_1st_surrogate_but_2nd_missing.json", rfc8259Embedded011iString1stSurrogateBut2ndMissingJson, 10U},
	{"i_string_1st_valid_surrogate_2nd_invalid.json", rfc8259Embedded012iString1stValidSurrogate2ndInvalidJson, 16U},
	{"i_string_UTF-16LE_with_BOM.json", rfc8259Embedded013iStringUTF16LEWithBOMJson, 12U},
	{"i_string_UTF-8_invalid_sequence.json", rfc8259Embedded014iStringUTF8InvalidSequenceJson, 10U},
	{"i_string_UTF8_surrogate_U+D800.json", rfc8259Embedded015iStringUTF8SurrogateUD800Json, 7U},
	{"i_string_incomplete_surrogate_and_escape_valid.json", rfc8259Embedded016iStringIncompleteSurrogateAndEscapeValidJson, 12U},
	{"i_string_incomplete_surrogate_pair.json", rfc8259Embedded017iStringIncompleteSurrogatePairJson, 11U},
	{"i_string_incomplete_surrogates_escape_valid.json", rfc8259Embedded018iStringIncompleteSurrogatesEscapeValidJson, 18U},
	{"i_string_invalid_lonely_surrogate.json", rfc8259Embedded019iStringInvalidLonelySurrogateJson, 10U},
	{"i_string_invalid_surrogate.json", rfc8259Embedded020iStringInvalidSurrogateJson, 13U},
	{"i_string_invalid_utf-8.json", rfc8259Embedded021iStringInvalidUtf8Json, 5U},
	{"i_string_inverted_surrogates_U+1D11E.json", rfc8259Embedded022iStringInvertedSurrogatesU1D11EJson, 16U},
	{"i_string_iso_latin_1.json", rfc8259Embedded023iStringIsoLatin1Json, 5U},
	{"i_string_lone_second_surrogate.json", rfc8259Embedded024iStringLoneSecondSurrogateJson, 10U},
	{"i_string_lone_utf8_continuation_byte.json", rfc8259Embedded025iStringLoneUtf8ContinuationByteJson, 5U},
	{"i_string_not_in_unicode_range.json", rfc8259Embedded026iStringNotInUnicodeRangeJson, 8U},
	{"i_string_overlong_sequence_2_bytes.json", rfc8259Embedded027iStringOverlongSequence2BytesJson, 6U},
	{"i_string_overlong_sequence_6_bytes.json", rfc8259Embedded028iStringOverlongSequence6BytesJson, 10U},
	{"i_string_overlong_sequence_6_bytes_null.json", rfc8259Embedded029iStringOverlongSequence6BytesNullJson, 10U},
	{"i_string_truncated-utf-8.json", rfc8259Embedded030iStringTruncatedUtf8Json, 6U},
	{"i_string_utf16BE_no_BOM.json", rfc8259Embedded031iStringUtf16BENoBOMJson, 10U},
	{"i_string_utf16LE_no_BOM.json", rfc8259Embedded032iStringUtf16LENoBOMJson, 10U},
	{"i_structure_UTF-8_BOM_empty_object.json", rfc8259Embedded033iStructureUTF8BOMEmptyObjectJson, 5U},
	{"n_array_1_true_without_comma.json", rfc8259Embedded034nArray1TrueWithoutCommaJson, 8U},
	{"n_array_a_invalid_utf8.json", rfc8259Embedded035nArrayAInvalidUtf8Json, 4U},
	{"n_array_colon_instead_of_comma.json", rfc8259Embedded036nArrayColonInsteadOfCommaJson, 7U},
	{"n_array_comma_after_close.json", rfc8259Embedded037nArrayCommaAfterCloseJson, 5U},
	{"n_array_comma_and_number.json", rfc8259Embedded038nArrayCommaAndNumberJson, 4U},
	{"n_array_double_comma.json", rfc8259Embedded039nArrayDoubleCommaJson, 6U},
	{"n_array_double_extra_comma.json", rfc8259Embedded040nArrayDoubleExtraCommaJson, 7U},
	{"n_array_extra_close.json", rfc8259Embedded041nArrayExtraCloseJson, 6U},
	{"n_array_extra_comma.json", rfc8259Embedded042nArrayExtraCommaJson, 5U},
	{"n_array_incomplete.json", rfc8259Embedded043nArrayIncompleteJson, 4U},
	{"n_array_incomplete_invalid_value.json", rfc8259Embedded044nArrayIncompleteInvalidValueJson, 2U},
	{"n_array_inner_array_no_comma.json", rfc8259Embedded045nArrayInnerArrayNoCommaJson, 6U},
	{"n_array_invalid_utf8.json", rfc8259Embedded046nArrayInvalidUtf8Json, 3U},
	{"n_array_items_separated_by_semicolon.json", rfc8259Embedded047nArrayItemsSeparatedBySemicolonJson, 5U},
	{"n_array_just_comma.json", rfc8259Embedded048nArrayJustCommaJson, 3U},
	{"n_array_just_minus.json", rfc8259Embedded049nArrayJustMinusJson, 3U},
	{"n_array_missing_value.json", rfc8259Embedded050nArrayMissingValueJson, 9U},
	{"n_array_newlines_unclosed.json", rfc8259Embedded051nArrayNewlinesUnclosedJson, 11U},
	{"n_array_number_and_comma.json", rfc8259Embedded052nArrayNumberAndCommaJson, 4U},
	{"n_array_number_and_several_commas.json", rfc8259Embedded053nArrayNumberAndSeveralCommasJson, 5U},
	{"n_array_spaces_vertical_tab_formfeed.json", rfc8259Embedded054nArraySpacesVerticalTabFormfeedJson, 8U},
	{"n_array_star_inside.json", rfc8259Embedded055nArrayStarInsideJson, 3U},
	{"n_array_unclosed.json", rfc8259Embedded056nArrayUnclosedJson, 3U},
	{"n_array_unclosed_trailing_comma.json", rfc8259Embedded057nArrayUnclosedTrailingCommaJson, 3U},
	{"n_array_unclosed_with_new_lines.json", rfc8259Embedded058nArrayUnclosedWithNewLinesJson, 8U},
	{"n_array_unclosed_with_object_inside.json", rfc8259Embedded059nArrayUnclosedWithObjectInsideJson, 3U},
	{"n_incomplete_false.json", rfc8259Embedded060nIncompleteFalseJson, 6U},
	{"n_incomplete_null.json", rfc8259Embedded061nIncompleteNullJson, 5U},
	{"n_incomplete_true.json", rfc8259Embedded062nIncompleteTrueJson, 5U},
	{"n_multidigit_number_then_00.json", rfc8259Embedded063nMultidigitNumberThen00Json, 4U},
	{"n_number_++.json", rfc8259Embedded064nNumberJson, 8U},
	{"n_number_+1.json", rfc8259Embedded065nNumber1Json, 4U},
	{"n_number_+Inf.json", rfc8259Embedded066nNumberInfJson, 6U},
	{"n_number_-01.json", rfc8259Embedded067nNumber01Json, 5U},
	{"n_number_-1.0..json", rfc8259Embedded068nNumber10Json, 7U},
	{"n_number_-2..json", rfc8259Embedded069nNumber2Json, 5U},
	{"n_number_-NaN.json", rfc8259Embedded070nNumberNaNJson, 6U},
	{"n_number_.-1.json", rfc8259Embedded071nNumber1Json, 5U},
	{"n_number_.2e-3.json", rfc8259Embedded072nNumber2e3Json, 7U},
	{"n_number_0.1.2.json", rfc8259Embedded073nNumber012Json, 7U},
	{"n_number_0.3e+.json", rfc8259Embedded074nNumber03eJson, 7U},
	{"n_number_0.3e.json", rfc8259Embedded075nNumber03eJson, 6U},
	{"n_number_0.e1.json", rfc8259Embedded076nNumber0E1Json, 6U},
	{"n_number_0_capital_E+.json", rfc8259Embedded077nNumber0CapitalEJson, 5U},
	{"n_number_0_capital_E.json", rfc8259Embedded078nNumber0CapitalEJson, 4U},
	{"n_number_0e+.json", rfc8259Embedded079nNumber0eJson, 5U},
	{"n_number_0e.json", rfc8259Embedded080nNumber0eJson, 4U},
	{"n_number_1.0e+.json", rfc8259Embedded081nNumber10eJson, 7U},
	{"n_number_1.0e-.json", rfc8259Embedded082nNumber10eJson, 7U},
	{"n_number_1.0e.json", rfc8259Embedded083nNumber10eJson, 6U},
	{"n_number_1_000.json", rfc8259Embedded084nNumber1000Json, 9U},
	{"n_number_1eE2.json", rfc8259Embedded085nNumber1eE2Json, 6U},
	{"n_number_2.e+3.json", rfc8259Embedded086nNumber2E3Json, 7U},
	{"n_number_2.e-3.json", rfc8259Embedded087nNumber2E3Json, 7U},
	{"n_number_2.e3.json", rfc8259Embedded088nNumber2E3Json, 6U},
	{"n_number_9.e+.json", rfc8259Embedded089nNumber9EJson, 6U},
	{"n_number_Inf.json", rfc8259Embedded090nNumberInfJson, 5U},
	{"n_number_NaN.json", rfc8259Embedded091nNumberNaNJson, 5U},
	{"n_number_U+FF11_fullwidth_digit_one.json", rfc8259Embedded092nNumberUFF11FullwidthDigitOneJson, 5U},
	{"n_number_expression.json", rfc8259Embedded093nNumberExpressionJson, 5U},
	{"n_number_hex_1_digit.json", rfc8259Embedded094nNumberHex1DigitJson, 5U},
	{"n_number_hex_2_digits.json", rfc8259Embedded095nNumberHex2DigitsJson, 6U},
	{"n_number_infinity.json", rfc8259Embedded096nNumberInfinityJson, 10U},
	{"n_number_invalid+-.json", rfc8259Embedded097nNumberInvalidJson, 7U},
	{"n_number_invalid-negative-real.json", rfc8259Embedded098nNumberInvalidNegativeRealJson, 13U},
	{"n_number_invalid-utf-8-in-bigger-int.json", rfc8259Embedded099nNumberInvalidUtf8InBiggerIntJson, 6U},
	{"n_number_invalid-utf-8-in-exponent.json", rfc8259Embedded100nNumberInvalidUtf8InExponentJson, 6U},
	{"n_number_invalid-utf-8-in-int.json", rfc8259Embedded101nNumberInvalidUtf8InIntJson, 5U},
	{"n_number_minus_infinity.json", rfc8259Embedded102nNumberMinusInfinityJson, 11U},
	{"n_number_minus_sign_with_trailing_garbage.json", rfc8259Embedded103nNumberMinusSignWithTrailingGarbageJson, 6U},
	{"n_number_minus_space_1.json", rfc8259Embedded104nNumberMinusSpace1Json, 5U},
	{"n_number_neg_int_starting_with_zero.json", rfc8259Embedded105nNumberNegIntStartingWithZeroJson, 6U},
	{"n_number_neg_real_without_int_part.json", rfc8259Embedded106nNumberNegRealWithoutIntPartJson, 7U},
	{"n_number_neg_with_garbage_at_end.json", rfc8259Embedded107nNumberNegWithGarbageAtEndJson, 5U},
	{"n_number_real_garbage_after_e.json", rfc8259Embedded108nNumberRealGarbageAfterEJson, 5U},
	{"n_number_real_with_invalid_utf8_after_e.json", rfc8259Embedded109nNumberRealWithInvalidUtf8AfterEJson, 5U},
	{"n_number_real_without_fractional_part.json", rfc8259Embedded110nNumberRealWithoutFractionalPartJson, 4U},
	{"n_number_starting_with_dot.json", rfc8259Embedded111nNumberStartingWithDotJson, 6U},
	{"n_number_with_alpha.json", rfc8259Embedded112nNumberWithAlphaJson, 8U},
	{"n_number_with_alpha_char.json", rfc8259Embedded113nNumberWithAlphaCharJson, 25U},
	{"n_number_with_leading_zero.json", rfc8259Embedded114nNumberWithLeadingZeroJson, 5U},
	{"n_object_bad_value.json", rfc8259Embedded115nObjectBadValueJson, 12U},
	{"n_object_bracket_key.json", rfc8259Embedded116nObjectBracketKeyJson, 9U},
	{"n_object_comma_instead_of_colon.json", rfc8259Embedded117nObjectCommaInsteadOfColonJson, 11U},
	{"n_object_double_colon.json", rfc8259Embedded118nObjectDoubleColonJson, 10U},
	{"n_object_emoji.json", rfc8259Embedded119nObjectEmojiJson, 10U},
	{"n_object_garbage_at_end.json", rfc8259Embedded120nObjectGarbageAtEndJson, 13U},
	{"n_object_key_with_single_quotes.json", rfc8259Embedded121nObjectKeyWithSingleQuotesJson, 14U},
	{"n_object_lone_continuation_byte_in_key_and_trailing_comma.json", rfc8259Embedded122nObjectLoneContinuationByteInKeyAndTrailingCommaJson, 10U},
	{"n_object_missing_colon.json", rfc8259Embedded123nObjectMissingColonJson, 7U},
	{"n_object_missing_key.json", rfc8259Embedded124nObjectMissingKeyJson, 6U},
	{"n_object_missing_semicolon.json", rfc8259Embedded125nObjectMissingSemicolonJson, 9U},
	{"n_object_missing_value.json", rfc8259Embedded126nObjectMissingValueJson, 5U},
	{"n_object_no-colon.json", rfc8259Embedded127nObjectNoColonJson, 4U},
	{"n_object_non_string_key.json", rfc8259Embedded128nObjectNonStringKeyJson, 5U},
	{"n_object_non_string_key_but_huge_number_instead.json", rfc8259Embedded129nObjectNonStringKeyButHugeNumberInsteadJson, 13U},
	{"n_object_repeated_null_null.json", rfc8259Embedded130nObjectRepeatedNullNullJson, 21U},
	{"n_object_several_trailing_commas.json", rfc8259Embedded131nObjectSeveralTrailingCommasJson, 13U},
	{"n_object_single_quote.json", rfc8259Embedded132nObjectSingleQuoteJson, 7U},
	{"n_object_trailing_comma.json", rfc8259Embedded133nObjectTrailingCommaJson, 9U},
	{"n_object_trailing_comment.json", rfc8259Embedded134nObjectTrailingCommentJson, 13U},
	{"n_object_trailing_comment_open.json", rfc8259Embedded135nObjectTrailingCommentOpenJson, 14U},
	{"n_object_trailing_comment_slash_open.json", rfc8259Embedded136nObjectTrailingCommentSlashOpenJson, 11U},
	{"n_object_trailing_comment_slash_open_incomplete.json", rfc8259Embedded137nObjectTrailingCommentSlashOpenIncompleteJson, 10U},
	{"n_object_two_commas_in_a_row.json", rfc8259Embedded138nObjectTwoCommasInARowJson, 18U},
	{"n_object_unquoted_key.json", rfc8259Embedded139nObjectUnquotedKeyJson, 8U},
	{"n_object_unterminated-value.json", rfc8259Embedded140nObjectUnterminatedValueJson, 7U},
	{"n_object_with_single_string.json", rfc8259Embedded141nObjectWithSingleStringJson, 22U},
	{"n_object_with_trailing_garbage.json", rfc8259Embedded142nObjectWithTrailingGarbageJson, 10U},
	{"n_single_space.json", rfc8259Embedded143nSingleSpaceJson, 1U},
	{"n_string_1_surrogate_then_escape.json", rfc8259Embedded144nString1SurrogateThenEscapeJson, 11U},
	{"n_string_1_surrogate_then_escape_u.json", rfc8259Embedded145nString1SurrogateThenEscapeUJson, 12U},
	{"n_string_1_surrogate_then_escape_u1.json", rfc8259Embedded146nString1SurrogateThenEscapeU1Json, 13U},
	{"n_string_1_surrogate_then_escape_u1x.json", rfc8259Embedded147nString1SurrogateThenEscapeU1xJson, 14U},
	{"n_string_accentuated_char_no_quotes.json", rfc8259Embedded148nStringAccentuatedCharNoQuotesJson, 4U},
	{"n_string_backslash_00.json", rfc8259Embedded149nStringBackslash00Json, 6U},
	{"n_string_escape_x.json", rfc8259Embedded150nStringEscapeXJson, 8U},
	{"n_string_escaped_backslash_bad.json", rfc8259Embedded151nStringEscapedBackslashBadJson, 7U},
	{"n_string_escaped_ctrl_char_tab.json", rfc8259Embedded152nStringEscapedCtrlCharTabJson, 6U},
	{"n_string_escaped_emoji.json", rfc8259Embedded153nStringEscapedEmojiJson, 9U},
	{"n_string_incomplete_escape.json", rfc8259Embedded154nStringIncompleteEscapeJson, 5U},
	{"n_string_incomplete_escaped_character.json", rfc8259Embedded155nStringIncompleteEscapedCharacterJson, 9U},
	{"n_string_incomplete_surrogate.json", rfc8259Embedded156nStringIncompleteSurrogateJson, 14U},
	{"n_string_incomplete_surrogate_escape_invalid.json", rfc8259Embedded157nStringIncompleteSurrogateEscapeInvalidJson, 18U},
	{"n_string_invalid-utf-8-in-escape.json", rfc8259Embedded158nStringInvalidUtf8InEscapeJson, 7U},
	{"n_string_invalid_backslash_esc.json", rfc8259Embedded159nStringInvalidBackslashEscJson, 6U},
	{"n_string_invalid_unicode_escape.json", rfc8259Embedded160nStringInvalidUnicodeEscapeJson, 10U},
	{"n_string_invalid_utf8_after_escape.json", rfc8259Embedded161nStringInvalidUtf8AfterEscapeJson, 6U},
	{"n_string_leading_uescaped_thinspace.json", rfc8259Embedded162nStringLeadingUescapedThinspaceJson, 13U},
	{"n_string_no_quotes_with_bad_escape.json", rfc8259Embedded163nStringNoQuotesWithBadEscapeJson, 4U},
	{"n_string_single_doublequote.json", rfc8259Embedded164nStringSingleDoublequoteJson, 1U},
	{"n_string_single_quote.json", rfc8259Embedded165nStringSingleQuoteJson, 16U},
	{"n_string_single_string_no_double_quotes.json", rfc8259Embedded166nStringSingleStringNoDoubleQuotesJson, 3U},
	{"n_string_start_escape_unclosed.json", rfc8259Embedded167nStringStartEscapeUnclosedJson, 3U},
	{"n_string_unescaped_ctrl_char.json", rfc8259Embedded168nStringUnescapedCtrlCharJson, 7U},
	{"n_string_unescaped_newline.json", rfc8259Embedded169nStringUnescapedNewlineJson, 12U},
	{"n_string_unescaped_tab.json", rfc8259Embedded170nStringUnescapedTabJson, 5U},
	{"n_string_unicode_CapitalU.json", rfc8259Embedded171nStringUnicodeCapitalUJson, 8U},
	{"n_string_with_trailing_garbage.json", rfc8259Embedded172nStringWithTrailingGarbageJson, 3U},
	{"n_structure_U+2060_word_joined.json", rfc8259Embedded173nStructureU2060WordJoinedJson, 5U},
	{"n_structure_UTF8_BOM_no_data.json", rfc8259Embedded174nStructureUTF8BOMNoDataJson, 3U},
	{"n_structure_angle_bracket_..json", rfc8259Embedded175nStructureAngleBracketJson, 3U},
	{"n_structure_angle_bracket_null.json", rfc8259Embedded176nStructureAngleBracketNullJson, 8U},
	{"n_structure_array_trailing_garbage.json", rfc8259Embedded177nStructureArrayTrailingGarbageJson, 4U},
	{"n_structure_array_with_extra_array_close.json", rfc8259Embedded178nStructureArrayWithExtraArrayCloseJson, 4U},
	{"n_structure_array_with_unclosed_string.json", rfc8259Embedded179nStructureArrayWithUnclosedStringJson, 6U},
	{"n_structure_ascii-unicode-identifier.json", rfc8259Embedded180nStructureAsciiUnicodeIdentifierJson, 3U},
	{"n_structure_capitalized_True.json", rfc8259Embedded181nStructureCapitalizedTrueJson, 6U},
	{"n_structure_close_unopened_array.json", rfc8259Embedded182nStructureCloseUnopenedArrayJson, 2U},
	{"n_structure_comma_instead_of_closing_brace.json", rfc8259Embedded183nStructureCommaInsteadOfClosingBraceJson, 11U},
	{"n_structure_double_array.json", rfc8259Embedded184nStructureDoubleArrayJson, 4U},
	{"n_structure_end_array.json", rfc8259Embedded185nStructureEndArrayJson, 1U},
	{"n_structure_incomplete_UTF8_BOM.json", rfc8259Embedded186nStructureIncompleteUTF8BOMJson, 4U},
	{"n_structure_lone-invalid-utf-8.json", rfc8259Embedded187nStructureLoneInvalidUtf8Json, 1U},
	{"n_structure_lone-open-bracket.json", rfc8259Embedded188nStructureLoneOpenBracketJson, 1U},
	{"n_structure_no_data.json", rfc8259Embedded189nStructureNoDataJson, 0U},
	{"n_structure_null-byte-outside-string.json", rfc8259Embedded190nStructureNullByteOutsideStringJson, 3U},
	{"n_structure_number_with_trailing_garbage.json", rfc8259Embedded191nStructureNumberWithTrailingGarbageJson, 2U},
	{"n_structure_object_followed_by_closing_object.json", rfc8259Embedded192nStructureObjectFollowedByClosingObjectJson, 3U},
	{"n_structure_object_unclosed_no_value.json", rfc8259Embedded193nStructureObjectUnclosedNoValueJson, 4U},
	{"n_structure_object_with_comment.json", rfc8259Embedded194nStructureObjectWithCommentJson, 20U},
	{"n_structure_object_with_trailing_garbage.json", rfc8259Embedded195nStructureObjectWithTrailingGarbageJson, 15U},
	{"n_structure_open_array_apostrophe.json", rfc8259Embedded196nStructureOpenArrayApostropheJson, 2U},
	{"n_structure_open_array_comma.json", rfc8259Embedded197nStructureOpenArrayCommaJson, 2U},
	{"n_structure_open_array_open_object.json", rfc8259Embedded198nStructureOpenArrayOpenObjectJson, 2U},
	{"n_structure_open_array_open_string.json", rfc8259Embedded199nStructureOpenArrayOpenStringJson, 3U},
	{"n_structure_open_array_string.json", rfc8259Embedded200nStructureOpenArrayStringJson, 4U},
	{"n_structure_open_object.json", rfc8259Embedded201nStructureOpenObjectJson, 1U},
	{"n_structure_open_object_close_array.json", rfc8259Embedded202nStructureOpenObjectCloseArrayJson, 2U},
	{"n_structure_open_object_comma.json", rfc8259Embedded203nStructureOpenObjectCommaJson, 2U},
	{"n_structure_open_object_open_array.json", rfc8259Embedded204nStructureOpenObjectOpenArrayJson, 2U},
	{"n_structure_open_object_open_string.json", rfc8259Embedded205nStructureOpenObjectOpenStringJson, 3U},
	{"n_structure_open_object_string_with_apostrophes.json", rfc8259Embedded206nStructureOpenObjectStringWithApostrophesJson, 4U},
	{"n_structure_open_open.json", rfc8259Embedded207nStructureOpenOpenJson, 16U},
	{"n_structure_single_eacute.json", rfc8259Embedded208nStructureSingleEacuteJson, 1U},
	{"n_structure_single_star.json", rfc8259Embedded209nStructureSingleStarJson, 1U},
	{"n_structure_trailing_#.json", rfc8259Embedded210nStructureTrailingJson, 12U},
	{"n_structure_uescaped_LF_before_string.json", rfc8259Embedded211nStructureUescapedLFBeforeStringJson, 10U},
	{"n_structure_unclosed_array.json", rfc8259Embedded212nStructureUnclosedArrayJson, 2U},
	{"n_structure_unclosed_array_partial_null.json", rfc8259Embedded213nStructureUnclosedArrayPartialNullJson, 12U},
	{"n_structure_unclosed_array_unfinished_false.json", rfc8259Embedded214nStructureUnclosedArrayUnfinishedFalseJson, 12U},
	{"n_structure_unclosed_array_unfinished_true.json", rfc8259Embedded215nStructureUnclosedArrayUnfinishedTrueJson, 12U},
	{"n_structure_unclosed_object.json", rfc8259Embedded216nStructureUnclosedObjectJson, 12U},
	{"n_structure_unicode-identifier.json", rfc8259Embedded217nStructureUnicodeIdentifierJson, 2U},
	{"n_structure_whitespace_U+2060_word_joiner.json", rfc8259Embedded218nStructureWhitespaceU2060WordJoinerJson, 5U},
	{"n_structure_whitespace_formfeed.json", rfc8259Embedded219nStructureWhitespaceFormfeedJson, 3U},
	{"y_1.json", rfc8259Embedded220y1Json, 16U},
	{"y_2.json", rfc8259Embedded221y2Json, 15U},
	{"y_3.json", rfc8259Embedded222y3Json, 18U},
	{"y_array_arraysWithSpaces.json", rfc8259Embedded223yArrayArraysWithSpacesJson, 7U},
	{"y_array_empty-string.json", rfc8259Embedded224yArrayEmptyStringJson, 4U},
	{"y_array_empty.json", rfc8259Embedded225yArrayEmptyJson, 2U},
	{"y_array_ending_with_newline.json", rfc8259Embedded226yArrayEndingWithNewlineJson, 5U},
	{"y_array_false.json", rfc8259Embedded227yArrayFalseJson, 7U},
	{"y_array_heterogeneous.json", rfc8259Embedded228yArrayHeterogeneousJson, 18U},
	{"y_array_nesting.json", rfc8259Embedded229yArrayNestingJson, 41U},
	{"y_array_null.json", rfc8259Embedded230yArrayNullJson, 6U},
	{"y_array_with_1_and_newline.json", rfc8259Embedded231yArrayWith1AndNewlineJson, 4U},
	{"y_array_with_leading_space.json", rfc8259Embedded232yArrayWithLeadingSpaceJson, 4U},
	{"y_array_with_several_null.json", rfc8259Embedded233yArrayWithSeveralNullJson, 20U},
	{"y_array_with_trailing_space.json", rfc8259Embedded234yArrayWithTrailingSpaceJson, 4U},
	{"y_number.json", rfc8259Embedded235yNumberJson, 8U},
	{"y_number_0e+1.json", rfc8259Embedded236yNumber0e1Json, 6U},
	{"y_number_0e1.json", rfc8259Embedded237yNumber0e1Json, 5U},
	{"y_number_after_space.json", rfc8259Embedded238yNumberAfterSpaceJson, 4U},
	{"y_number_double_close_to_zero.json", rfc8259Embedded239yNumberDoubleCloseToZeroJson, 84U},
	{"y_number_int_with_exp.json", rfc8259Embedded240yNumberIntWithExpJson, 6U},
	{"y_number_minus_zero.json", rfc8259Embedded241yNumberMinusZeroJson, 4U},
	{"y_number_negative_int.json", rfc8259Embedded242yNumberNegativeIntJson, 6U},
	{"y_number_negative_one.json", rfc8259Embedded243yNumberNegativeOneJson, 4U},
	{"y_number_negative_zero.json", rfc8259Embedded244yNumberNegativeZeroJson, 4U},
	{"y_number_real_capital_e.json", rfc8259Embedded245yNumberRealCapitalEJson, 6U},
	{"y_number_real_capital_e_neg_exp.json", rfc8259Embedded246yNumberRealCapitalENegExpJson, 6U},
	{"y_number_real_capital_e_pos_exp.json", rfc8259Embedded247yNumberRealCapitalEPosExpJson, 6U},
	{"y_number_real_exponent.json", rfc8259Embedded248yNumberRealExponentJson, 8U},
	{"y_number_real_fraction_exponent.json", rfc8259Embedded249yNumberRealFractionExponentJson, 12U},
	{"y_number_real_neg_exp.json", rfc8259Embedded250yNumberRealNegExpJson, 6U},
	{"y_number_real_pos_exponent.json", rfc8259Embedded251yNumberRealPosExponentJson, 6U},
	{"y_number_simple_int.json", rfc8259Embedded252yNumberSimpleIntJson, 5U},
	{"y_number_simple_real.json", rfc8259Embedded253yNumberSimpleRealJson, 12U},
	{"y_object.json", rfc8259Embedded254yObjectJson, 26U},
	{"y_object_basic.json", rfc8259Embedded255yObjectBasicJson, 13U},
	{"y_object_duplicated_key.json", rfc8259Embedded256yObjectDuplicatedKeyJson, 17U},
	{"y_object_duplicated_key_and_value.json", rfc8259Embedded257yObjectDuplicatedKeyAndValueJson, 17U},
	{"y_object_empty.json", rfc8259Embedded258yObjectEmptyJson, 2U},
	{"y_object_empty_key.json", rfc8259Embedded259yObjectEmptyKeyJson, 6U},
	{"y_object_escaped_null_in_key.json", rfc8259Embedded260yObjectEscapedNullInKeyJson, 20U},
	{"y_object_extreme_numbers.json", rfc8259Embedded261yObjectExtremeNumbersJson, 35U},
	{"y_object_long_strings.json", rfc8259Embedded262yObjectLongStringsJson, 108U},
	{"y_object_simple.json", rfc8259Embedded263yObjectSimpleJson, 8U},
	{"y_object_string_unicode.json", rfc8259Embedded264yObjectStringUnicodeJson, 110U},
	{"y_object_with_newlines.json", rfc8259Embedded265yObjectWithNewlinesJson, 12U},
	{"y_string_1_2_3_bytes_UTF-8_sequences.json", rfc8259Embedded266yString123BytesUTF8SequencesJson, 22U},
	{"y_string_accepted_surrogate_pair.json", rfc8259Embedded267yStringAcceptedSurrogatePairJson, 16U},
	{"y_string_accepted_surrogate_pairs.json", rfc8259Embedded268yStringAcceptedSurrogatePairsJson, 28U},
	{"y_string_allowed_escapes.json", rfc8259Embedded269yStringAllowedEscapesJson, 20U},
	{"y_string_backslash_and_u_escaped_zero.json", rfc8259Embedded270yStringBackslashAndUEscapedZeroJson, 11U},
	{"y_string_backslash_doublequotes.json", rfc8259Embedded271yStringBackslashDoublequotesJson, 6U},
	{"y_string_comments.json", rfc8259Embedded272yStringCommentsJson, 17U},
	{"y_string_double_escape_a.json", rfc8259Embedded273yStringDoubleEscapeAJson, 7U},
	{"y_string_double_escape_n.json", rfc8259Embedded274yStringDoubleEscapeNJson, 7U},
	{"y_string_escaped_control_character.json", rfc8259Embedded275yStringEscapedControlCharacterJson, 10U},
	{"y_string_escaped_noncharacter.json", rfc8259Embedded276yStringEscapedNoncharacterJson, 10U},
	{"y_string_in_array.json", rfc8259Embedded277yStringInArrayJson, 7U},
	{"y_string_in_array_with_leading_space.json", rfc8259Embedded278yStringInArrayWithLeadingSpaceJson, 8U},
	{"y_string_last_surrogates_1_and_2.json", rfc8259Embedded279yStringLastSurrogates1And2Json, 16U},
	{"y_string_nbsp_uescaped.json", rfc8259Embedded280yStringNbspUescapedJson, 17U},
	{"y_string_nonCharacterInUTF-8_U+10FFFF.json", rfc8259Embedded281yStringNonCharacterInUTF8U10FFFFJson, 8U},
	{"y_string_nonCharacterInUTF-8_U+FFFF.json", rfc8259Embedded282yStringNonCharacterInUTF8UFFFFJson, 7U},
	{"y_string_null_escape.json", rfc8259Embedded283yStringNullEscapeJson, 10U},
	{"y_string_one-byte-utf-8.json", rfc8259Embedded284yStringOneByteUtf8Json, 10U},
	{"y_string_pi.json", rfc8259Embedded285yStringPiJson, 6U},
	{"y_string_reservedCharacterInUTF-8_U+1BFFF.json", rfc8259Embedded286yStringReservedCharacterInUTF8U1BFFFJson, 8U},
	{"y_string_simple_ascii.json", rfc8259Embedded287yStringSimpleAsciiJson, 8U},
	{"y_string_space.json", rfc8259Embedded288yStringSpaceJson, 3U},
	{"y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF.json", rfc8259Embedded289yStringSurrogatesU1D11EMUSICALSYMBOLGCLEFJson, 16U},
	{"y_string_three-byte-utf-8.json", rfc8259Embedded290yStringThreeByteUtf8Json, 10U},
	{"y_string_two-byte-utf-8.json", rfc8259Embedded291yStringTwoByteUtf8Json, 10U},
	{"y_string_u+2028_line_sep.json", rfc8259Embedded292yStringU2028LineSepJson, 7U},
	{"y_string_u+2029_par_sep.json", rfc8259Embedded293yStringU2029ParSepJson, 7U},
	{"y_string_uEscape.json", rfc8259Embedded294yStringUEscapeJson, 28U},
	{"y_string_uescaped_newline.json", rfc8259Embedded295yStringUescapedNewlineJson, 17U},
	{"y_string_unescaped_char_delete.json", rfc8259Embedded296yStringUnescapedCharDeleteJson, 5U},
	{"y_string_unicode.json", rfc8259Embedded297yStringUnicodeJson, 10U},
	{"y_string_unicodeEscapedBackslash.json", rfc8259Embedded298yStringUnicodeEscapedBackslashJson, 10U},
	{"y_string_unicode_2.json", rfc8259Embedded299yStringUnicode2Json, 13U},
	{"y_string_unicode_U+10FFFE_nonchar.json", rfc8259Embedded300yStringUnicodeU10FFFENoncharJson, 16U},
	{"y_string_unicode_U+1FFFE_nonchar.json", rfc8259Embedded301yStringUnicodeU1FFFENoncharJson, 16U},
	{"y_string_unicode_U+200B_ZERO_WIDTH_SPACE.json", rfc8259Embedded302yStringUnicodeU200BZEROWIDTHSPACEJson, 10U},
	{"y_string_unicode_U+2064_invisible_plus.json", rfc8259Embedded303yStringUnicodeU2064InvisiblePlusJson, 10U},
	{"y_string_unicode_U+FDD0_nonchar.json", rfc8259Embedded304yStringUnicodeUFDD0NoncharJson, 10U},
	{"y_string_unicode_U+FFFE_nonchar.json", rfc8259Embedded305yStringUnicodeUFFFENoncharJson, 10U},
	{"y_string_unicode_escaped_double_quote.json", rfc8259Embedded306yStringUnicodeEscapedDoubleQuoteJson, 10U},
	{"y_string_utf8.json", rfc8259Embedded307yStringUtf8Json, 11U},
	{"y_string_with_del_character.json", rfc8259Embedded308yStringWithDelCharacterJson, 7U},
	{"y_structure_lonely_false.json", rfc8259Embedded309yStructureLonelyFalseJson, 5U},
	{"y_structure_lonely_int.json", rfc8259Embedded310yStructureLonelyIntJson, 2U},
	{"y_structure_lonely_negative_real.json", rfc8259Embedded311yStructureLonelyNegativeRealJson, 4U},
	{"y_structure_lonely_null.json", rfc8259Embedded312yStructureLonelyNullJson, 4U},
	{"y_structure_lonely_string.json", rfc8259Embedded313yStructureLonelyStringJson, 5U},
	{"y_structure_lonely_true.json", rfc8259Embedded314yStructureLonelyTrueJson, 4U},
	{"y_structure_string_empty.json", rfc8259Embedded315yStructureStringEmptyJson, 2U},
	{"y_structure_trailing_newline.json", rfc8259Embedded316yStructureTrailingNewlineJson, 6U},
	{"y_structure_true_in_array.json", rfc8259Embedded317yStructureTrueInArrayJson, 6U},
	{"y_structure_whitespace_array.json", rfc8259Embedded318yStructureWhitespaceArrayJson, 4U},
};

const uint32_t gRfc8259EmbeddedFileCount = (uint32_t)(sizeof(gRfc8259EmbeddedFiles) / sizeof(gRfc8259EmbeddedFiles[0]));
